lab2
EvgeniyVashinko/Android-labs pull request #4
Opened 2020-12-14 16:22 UTC by EvgeniyVashinko

lab2

2020-12-17 14:58 UTC, gmltA requested changes
Not bad. But I want to see some minor improvements first.

2020-12-17 14:58 UTC, gmltA commented on lab2/SuperTimer/app/src/main/java/com/example/supertimer/data/TimerDao.java
> +    @Query("SELECT * FROM timer WHERE id LIKE :timerId LIMIT 1")
Why do use `LIKE` here?

2020-12-17 14:58 UTC, gmltA commented on lab2/SuperTimer/app/src/main/java/com/example/supertimer/view/main/MainActivity.java
> +        }
Can you extract identical customisation code into abstract Activity class and inherit it everywhere you need it?

2020-12-17 14:58 UTC, gmltA commented on lab2/SuperTimer/app/src/main/java/com/example/supertimer/view/main/TimerAdapter.java
> +        this.size = 12;
This thing doesn't look good either.

2020-12-17 18:14 UTC, EvgeniyVashinko commented on lab2/SuperTimer/app/src/main/java/com/example/supertimer/view/main/MainActivity.java
> +        }
sounds good

2020-12-17 18:15 UTC, EvgeniyVashinko commented on lab2/SuperTimer/app/src/main/java/com/example/supertimer/data/TimerDao.java
> +    @Query("SELECT * FROM timer WHERE id LIKE :timerId LIMIT 1")
when i read documentation for room, i saw a class-example there. i copied and fixed it for my application to save time. 
in this case we can replace LIKE with '='

2020-12-17 18:16 UTC, EvgeniyVashinko commented on lab2/SuperTimer/app/src/main/java/com/example/supertimer/view/main/TimerAdapter.java
> +        this.size = 12;
i fixed it

2020-12-17 18:34 UTC, EvgeniyVashinko commented
I passed 1st and 3rd labs. Is it all?

2020-12-18 13:41 UTC, gmltA approved these changes
That's it. Good luck!

2020-12-18 14:16 UTC, EvgeniyVashinko commented
Thanks, you too

2020-12-18 14:22 UTC, merged